export interface ThemeConfig {
  name: string;
  url: string;
  bg: string;
  fg: string;
  tier: 'free' | 'pro';
}

const CDN_BASE = 'https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.11.1/styles';

export const themes: Record<string, ThemeConfig> = {
  // ========== Free Themes (10) ==========
  default: {
    name: 'Default',
    url: `${CDN_BASE}/default.min.css`,
    bg: '#f0f0f0',
    fg: '#444444',
    tier: 'free',
  },
  'atom-one-dark': {
    name: 'Atom One Dark',
    url: `${CDN_BASE}/atom-one-dark.min.css`,
    bg: '#282c34',
    fg: '#abb2bf',
    tier: 'free',
  },
  monokai: {
    name: 'Monokai',
    url: `${CDN_BASE}/monokai.min.css`,
    bg: '#272822',
    fg: '#f8f8f2',
    tier: 'free',
  },
  'github-dark': {
    name: 'GitHub Dark',
    url: `${CDN_BASE}/github-dark.min.css`,
    bg: '#0d1117',
    fg: '#c9d1d9',
    tier: 'free',
  },
  github: {
    name: 'GitHub Light',
    url: `${CDN_BASE}/github.min.css`,
    bg: '#ffffff',
    fg: '#24292e',
    tier: 'free',
  },
  'atom-one-light': {
    name: 'Atom One Light',
    url: `${CDN_BASE}/atom-one-light.min.css`,
    bg: '#fafafa',
    fg: '#383a42',
    tier: 'free',
  },
  dracula: {
    name: 'Dracula',
    url: `${CDN_BASE}/dracula.min.css`,
    bg: '#282a36',
    fg: '#f8f8f2',
    tier: 'free',
  },
  nord: {
    name: 'Nord',
    url: `${CDN_BASE}/nord.min.css`,
    bg: '#2e3440',
    fg: '#d8dee9',
    tier: 'free',
  },
  'tokyo-night-dark': {
    name: 'Tokyo Night Dark',
    url: `${CDN_BASE}/tokyo-night-dark.min.css`,
    bg: '#1a1b26',
    fg: '#a9b1d6',
    tier: 'free',
  },
  'tokyo-night-light': {
    name: 'Tokyo Night Light',
    url: `${CDN_BASE}/tokyo-night-light.min.css`,
    bg: '#d5d6db',
    fg: '#343b58',
    tier: 'free',
  },

  // ========== Pro Themes (45) ==========
  'a11y-dark': {
    name: 'A11y Dark',
    url: `${CDN_BASE}/a11y-dark.min.css`,
    bg: '#2b2b2b',
    fg: '#f8f8f2',
    tier: 'pro',
  },
  'a11y-light': {
    name: 'A11y Light',
    url: `${CDN_BASE}/a11y-light.min.css`,
    bg: '#fefefe',
    fg: '#545454',
    tier: 'pro',
  },
  agate: {
    name: 'Agate',
    url: `${CDN_BASE}/agate.min.css`,
    bg: '#333333',
    fg: '#ffffff',
    tier: 'pro',
  },
  'an-old-hope': {
    name: 'An Old Hope',
    url: `${CDN_BASE}/an-old-hope.min.css`,
    bg: '#1c1d21',
    fg: '#c0c5ce',
    tier: 'pro',
  },
  androidstudio: {
    name: 'Android Studio',
    url: `${CDN_BASE}/androidstudio.min.css`,
    bg: '#282b2e',
    fg: '#a9b7c6',
    tier: 'pro',
  },
  'arduino-light': {
    name: 'Arduino Light',
    url: `${CDN_BASE}/arduino-light.min.css`,
    bg: '#ffffff',
    fg: '#434f54',
    tier: 'pro',
  },
  arta: {
    name: 'Arta',
    url: `${CDN_BASE}/arta.min.css`,
    bg: '#222222',
    fg: '#aaaaaa',
    tier: 'pro',
  },
  ascetic: {
    name: 'Ascetic',
    url: `${CDN_BASE}/ascetic.min.css`,
    bg: '#ffffff',
    fg: '#000000',
    tier: 'pro',
  },
  'brown-paper': {
    name: 'Brown Paper',
    url: `${CDN_BASE}/brown-paper.min.css`,
    bg: '#b7a68e',
    fg: '#363c69',
    tier: 'pro',
  },
  'codepen-embed': {
    name: 'CodePen Embed',
    url: `${CDN_BASE}/codepen-embed.min.css`,
    bg: '#222222',
    fg: '#ffffff',
    tier: 'pro',
  },
  'color-brewer': {
    name: 'Color Brewer',
    url: `${CDN_BASE}/color-brewer.min.css`,
    bg: '#ffffff',
    fg: '#000000',
    tier: 'pro',
  },
  dark: {
    name: 'Dark',
    url: `${CDN_BASE}/dark.min.css`,
    bg: '#444444',
    fg: '#dddddd',
    tier: 'pro',
  },
  devibeans: {
    name: 'Devibeans',
    url: `${CDN_BASE}/devibeans.min.css`,
    bg: '#000000',
    fg: '#d0d0d0',
    tier: 'pro',
  },
  docco: {
    name: 'Docco',
    url: `${CDN_BASE}/docco.min.css`,
    bg: '#f8f8ff',
    fg: '#000000',
    tier: 'pro',
  },
  far: {
    name: 'Far',
    url: `${CDN_BASE}/far.min.css`,
    bg: '#000080',
    fg: '#00ffff',
    tier: 'pro',
  },
  felipec: {
    name: 'Felipec',
    url: `${CDN_BASE}/felipec.min.css`,
    bg: '#2b2b2b',
    fg: '#d4d4d4',
    tier: 'pro',
  },
  foundation: {
    name: 'Foundation',
    url: `${CDN_BASE}/foundation.min.css`,
    bg: '#eeeeee',
    fg: '#000000',
    tier: 'pro',
  },
  'github-dark-dimmed': {
    name: 'GitHub Dark Dimmed',
    url: `${CDN_BASE}/github-dark-dimmed.min.css`,
    bg: '#22272e',
    fg: '#adbac7',
    tier: 'pro',
  },
  gml: {
    name: 'GML',
    url: `${CDN_BASE}/gml.min.css`,
    bg: '#222222',
    fg: '#c0c0c0',
    tier: 'pro',
  },
  googlecode: {
    name: 'Google Code',
    url: `${CDN_BASE}/googlecode.min.css`,
    bg: '#ffffff',
    fg: '#000000',
    tier: 'pro',
  },
  'gradient-dark': {
    name: 'Gradient Dark',
    url: `${CDN_BASE}/gradient-dark.min.css`,
    bg: '#1e1e1e',
    fg: '#e0e0e0',
    tier: 'pro',
  },
  'gradient-light': {
    name: 'Gradient Light',
    url: `${CDN_BASE}/gradient-light.min.css`,
    bg: '#f9f9f9',
    fg: '#333333',
    tier: 'pro',
  },
  grayscale: {
    name: 'Grayscale',
    url: `${CDN_BASE}/grayscale.min.css`,
    bg: '#ffffff',
    fg: '#333333',
    tier: 'pro',
  },
  hybrid: {
    name: 'Hybrid',
    url: `${CDN_BASE}/hybrid.min.css`,
    bg: '#1d1f21',
    fg: '#c5c8c6',
    tier: 'pro',
  },
  idea: {
    name: 'IDEA',
    url: `${CDN_BASE}/idea.min.css`,
    bg: '#ffffff',
    fg: '#000000',
    tier: 'pro',
  },
  'intellij-light': {
    name: 'IntelliJ Light',
    url: `${CDN_BASE}/intellij-light.min.css`,
    bg: '#ffffff',
    fg: '#000000',
    tier: 'pro',
  },
  'ir-black': {
    name: 'IR Black',
    url: `${CDN_BASE}/ir-black.min.css`,
    bg: '#000000',
    fg: '#f6f3e8',
    tier: 'pro',
  },
  'isbl-editor-dark': {
    name: 'ISBL Editor Dark',
    url: `${CDN_BASE}/isbl-editor-dark.min.css`,
    bg: '#404040',
    fg: '#ffffff',
    tier: 'pro',
  },
  'isbl-editor-light': {
    name: 'ISBL Editor Light',
    url: `${CDN_BASE}/isbl-editor-light.min.css`,
    bg: '#ffffff',
    fg: '#000000',
    tier: 'pro',
  },
  'kimbie-dark': {
    name: 'Kimbie Dark',
    url: `${CDN_BASE}/kimbie-dark.min.css`,
    bg: '#221a0f',
    fg: '#d3af86',
    tier: 'pro',
  },
  'kimbie-light': {
    name: 'Kimbie Light',
    url: `${CDN_BASE}/kimbie-light.min.css`,
    bg: '#fbebd4',
    fg: '#84613d',
    tier: 'pro',
  },
  lightfair: {
    name: 'Lightfair',
    url: `${CDN_BASE}/lightfair.min.css`,
    bg: '#ffffff',
    fg: '#000000',
    tier: 'pro',
  },
  lioshi: {
    name: 'Lioshi',
    url: `${CDN_BASE}/lioshi.min.css`,
    bg: '#222222',
    fg: '#bfbfbf',
    tier: 'pro',
  },
  magula: {
    name: 'Magula',
    url: `${CDN_BASE}/magula.min.css`,
    bg: '#f4f4f4',
    fg: '#000000',
    tier: 'pro',
  },
  'monokai-sublime': {
    name: 'Monokai Sublime',
    url: `${CDN_BASE}/monokai-sublime.min.css`,
    bg: '#23241f',
    fg: '#f8f8f2',
    tier: 'pro',
  },
  'nnfx-dark': {
    name: 'NNFX Dark',
    url: `${CDN_BASE}/nnfx-dark.min.css`,
    bg: '#333333',
    fg: '#ffffff',
    tier: 'pro',
  },
  'nnfx-light': {
    name: 'NNFX Light',
    url: `${CDN_BASE}/nnfx-light.min.css`,
    bg: '#ffffff',
    fg: '#000000',
    tier: 'pro',
  },
  obsidian: {
    name: 'Obsidian',
    url: `${CDN_BASE}/obsidian.min.css`,
    bg: '#293134',
    fg: '#e0e2e4',
    tier: 'pro',
  },
  'panda-syntax-dark': {
    name: 'Panda Syntax Dark',
    url: `${CDN_BASE}/panda-syntax-dark.min.css`,
    bg: '#1d1f21',
    fg: '#e6e6e6',
    tier: 'pro',
  },
  'panda-syntax-light': {
    name: 'Panda Syntax Light',
    url: `${CDN_BASE}/panda-syntax-light.min.css`,
    bg: '#fafafa',
    fg: '#2a2c2d',
    tier: 'pro',
  },
  'paraiso-dark': {
    name: 'Paraiso Dark',
    url: `${CDN_BASE}/paraiso-dark.min.css`,
    bg: '#2f1e2e',
    fg: '#a39e9b',
    tier: 'pro',
  },
  'paraiso-light': {
    name: 'Paraiso Light',
    url: `${CDN_BASE}/paraiso-light.min.css`,
    bg: '#e7e9db',
    fg: '#4f424c',
    tier: 'pro',
  },
  pojoaque: {
    name: 'Pojoaque',
    url: `${CDN_BASE}/pojoaque.min.css`,
    bg: '#2c2c2c',
    fg: '#dccf8f',
    tier: 'pro',
  },
  purebasic: {
    name: 'PureBasic',
    url: `${CDN_BASE}/purebasic.min.css`,
    bg: '#ffffdf',
    fg: '#000000',
    tier: 'pro',
  },
  'qtcreator-dark': {
    name: 'Qt Creator Dark',
    url: `${CDN_BASE}/qtcreator-dark.min.css`,
    bg: '#000000',
    fg: '#aaaaaa',
    tier: 'pro',
  },
};

export type ThemeKey = keyof typeof themes;

export const languages = [
  { key: 'javascript', name: 'JavaScript' },
  { key: 'typescript', name: 'TypeScript' },
  { key: 'python', name: 'Python' },
  { key: 'java', name: 'Java' },
  { key: 'cpp', name: 'C++' },
  { key: 'c', name: 'C' },
  { key: 'csharp', name: 'C#' },
  { key: 'go', name: 'Go' },
  { key: 'rust', name: 'Rust' },
  { key: 'php', name: 'PHP' },
  { key: 'ruby', name: 'Ruby' },
  { key: 'swift', name: 'Swift' },
  { key: 'kotlin', name: 'Kotlin' },
  { key: 'html', name: 'HTML' },
  { key: 'css', name: 'CSS' },
  { key: 'sql', name: 'SQL' },
  { key: 'bash', name: 'Bash' },
  { key: 'json', name: 'JSON' },
  { key: 'xml', name: 'XML' },
  { key: 'yaml', name: 'YAML' },
];
